### ISSUE TITLE
The specified internal directory should be fully accessible to the remoting executable (RWX)

### ISSUE THREAD

**Issue by GetchaDEAGLE** [KostyaSha/yet-another-docker-plugin#184] opened 2017-08-17 04:49 UTC
Upon upgrading to the latest version of Jenkins (v2.74), I am getting the following message when doing builds using JNLP slaves:

> INFO: Jenkins agent is running in headless mode.
Exception in thread "main" java.io.IOException: The specified remoting internal directory should be fully accessible to the remoting executable (RWX): /
        at org.jenkinsci.remoting.engine.WorkDirManager.verifyDirectory(WorkDirManager.java:232)
        at org.jenkinsci.remoting.engine.WorkDirManager.initializeWorkDir(WorkDirManager.java:190)
        at hudson.remoting.Engine.startEngine(Engine.java:252)
        at hudson.remoting.Engine.startEngine(Engine.java:229)
        at hudson.remoting.jnlp.Main.main(Main.java:217)
        at hudson.remoting.jnlp.Main._main(Main.java:212)
        at hudson.remoting.Launcher.run(Launcher.java:351)
        at hudson.remoting.Launcher.main(Launcher.java:277)

If I revert back to my previous version (Jenkins v2.46.1), it works just fine. I'm rather perplexed by this and have spent hours searching for a resolution to this problem but cannot find one. It appears to be some sort of permissions problem but I have checked that and nothing has changed for this.

Has anyone run into this issue yet?

**Comment by witokondoria** [comment] 2017-08-17 07:55
That issue seems related to a [remoting change](https://github.com/jenkinsci/remoting/blob/master/docs/workDir.md) at Jenkins 2.72.

As a workaround, you can define the workdir at the JNLP settings,  Slave (slave.jar) options `-workDir /home/jenkins`

I didnt reach to guess why is it trying to use the filesystem root `/` as default workspace

**Comment by GetchaDEAGLE** [comment] 2017-08-17 09:28
@witokondoria, I am beyond grateful for your help with that. I spent a very long time trying to figure this out and have found that the variables involved sometimes are countless. Thanks for taking the time to assist. I'm sure this will help others with this problem.

**Comment by KostyaSha** [comment] 2017-08-17 09:31
Let's wait until @oleg-nenashev update YAD in one of his installations :)

**Comment by oleg-nenashev** [comment] 2017-08-17 12:39
@KostyaSha yep, it smells like a valid regression, but the launcher config should not enable workdir by default in your launcher. Will try to check why it happens by Monday

**Comment by KostyaSha** [comment] 2017-08-17 15:48
> I didnt reach to guess why is it trying to use the filesystem root / as default workspace

https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/resources/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher/init.sh#L44-L49
Script do `cd` into directory. Only if home directory become `/` but then build wouldn't work.

**Comment by witokondoria** [comment] 2017-08-17 18:32
I would say my JENKINS_HOME is defined to /var/lib/jenkins, being an already existing directory (but would have to double check it)

**Comment by oleg-nenashev** [comment] 2017-08-17 18:37
@GetchaDEAGLE Please provide your YAD Cloud config XML

**Comment by GetchaDEAGLE** [comment] 2017-08-25 19:21
@oleg-nenashev, sounds good. Would you be able to give me the location so I can send the right info? Thanks.

**Comment by witokondoria** [comment] 2017-08-28 21:28
@GetchaDEAGLE, you can just paste it to a [gist](https://gist.github.com/) (I dont currently have access to read my config)

**Comment by 1arrow** [comment] 2017-08-29 22:30
I am facing this issue to with recent jenkins upgrade

**Comment by KostyaSha** [comment] 2017-09-03 00:44
adding debug code https://github.com/KostyaSha/yet-another-docker-plugin/commit/9db0eb8dd470d7ac63ea46b5fabd7d5835451d9f

**Comment by KostyaSha** [comment] 2017-09-06 00:24
Could you try latest version?

**Comment by GetchaDEAGLE** [comment] 2017-09-06 23:55
@witokondoria, sorry for my delayed response as I've been super busy lately. What I need to know is where the exact file for YAD Cloud Config XML exists inside of Jenkins. I'd be happy to post that information if still necessary.

Also, I'm rather inclined to keep the slave.jar -workDir /home/jenkins option as it's very explicit and I may never need to worry about it not defaulting to the proper directory again if I keep it there.

**Comment by GetchaDEAGLE** [comment] 2017-09-06 23:56
@KostyaSha, I will remove the slave.jar -workDir /home/jenkins option and try the latest version soon. I'll let you know what I come up with.

**Comment by witokondoria** [comment] 2017-09-07 06:44
@GetchaDEAGLE its located at $JENKINS_HOME/config.xml, under a tag <com.github.kostyasha.yad.DockerCloud plugin="yet-another-docker-plugin@0.1.0-rc38"> (or the appropiate version)

@oleg-nenashev, my config, on the previous YAD release is at [a gist](https://gist.github.com/witokondoria/cd9e56961e24ce8469f6add7bf6b9646)

**Comment by samrocketman** [comment] 2017-09-24 04:38
This issue now affects yet-another-docker-plugin on LTS Jenkins  2.73.1.

**Comment by samrocketman** [comment] 2017-09-24 04:56
The workaround outlined in https://github.com/KostyaSha/yet-another-docker-plugin/issues/184#issuecomment-322996960 fixed it for me as well.  This should probably be addressed now that the issue has reached LTS.

**Comment by GetchaDEAGLE** [comment] 2017-10-05 04:44
Sorry for not getting the config.xml to you guys sooner. I have still been swamped in a work-related project. Hopefully this helps.

`<com.github.kostyasha.yad.DockerCloud plugin="yet-another-docker-plugin@0.1.0-rc42">
      <name>Spacely-Sprockets</name>
      <provisionedImages/>
      <templates>
        <com.github.kostyasha.yad.DockerSlaveTemplate>
          <id>redacted</id>
          <labelString>jenkins-slave-container</labelString>
          <launcher class="com.github.kostyasha.yad.launcher.DockerComputerJNLPLauncher">
            <launchTimeout>120</launchTimeout>
            <user>jenkins</user>
            <jvmOpts>-Xmx8192m -Djava.awt.headless=true -Duser.timezone=America/Chicago -Djavax.net.ssl.trustStore=/etc/ssl/java/truststore/cacerts</jvmOpts>
            <slaveOpts></slaveOpts>
            <jenkinsUrl>https://jenkins-nginx.dev.internal.spacely-sprockets.com</jenkinsUrl>
            <noCertificateCheck>false</noCertificateCheck>
            <reconnect>false</reconnect>
          </launcher>
          <remoteFs>/home/jenkins</remoteFs>
          <mode>EXCLUSIVE</mode>
          <retentionStrategy class="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>0</idleMinutes>
            <idleMinutes defined-in="com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy">10</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
          <dockerContainerLifecycle>
            <image>danieleagle/jenkins-slave:8u131-jdk-alpine</image>
            <pullImage>
              <pullStrategy>PULL_NEVER</pullStrategy>
              <credentialsId></credentialsId>
            </pullImage>
            <createContainer>
              <command></command>
              <hostname></hostname>
              <dnsHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </dnsHosts>
              <volumes class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list">
                  <string>/var/run/docker.sock:/var/run/docker.sock</string>
                  <string>/docker-data/jenkins/jenkins-slave/volume_data/truststore:/etc/ssl/java/truststore:ro</string>
                  <string>/docker-data/jenkins/jenkins-slave/volume_data/ssl:/etc/ssl/certs:ro</string>
                </c>
                <list reference="../c"/>
              </volumes>
              <volumesFrom class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </volumesFrom>
              <environment class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </environment>
              <bindPorts></bindPorts>
              <bindAllPorts>false</bindAllPorts>
              <memoryLimit>0</memoryLimit>
              <privileged>false</privileged>
              <tty>false</tty>
              <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </extraHosts>
              <networkMode>dev-net</networkMode>
              <devices class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </devices>
              <cpusetCpus></cpusetCpus>
              <cpusetMems></cpusetMems>
              <links class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
                <c class="list"/>
                <list reference="../c"/>
              </links>
              <shmSize>0</shmSize>
              <restartPolicy>
                <policyName>NO</policyName>
                <maximumRetryCount>0</maximumRetryCount>
              </restartPolicy>
              <workdir></workdir>
              <user></user>
            </createContainer>
            <stopContainer>
              <timeout>10</timeout>
            </stopContainer>
            <removeContainer>
              <removeVolumes>true</removeVolumes>
              <force>false</force>
            </removeContainer>
          </dockerContainerLifecycle>
          <maxCapacity>50</maxCapacity>
        </com.github.kostyasha.yad.DockerSlaveTemplate>
      </templates>
      <containerCap>50</containerCap>
      <connector>
        <serverUrl>tcp://10.0.0.12:2376</serverUrl>
        <credentialsId>redacted</credentialsId>
        <connectorType>NETTY</connectorType>
      </connector>
    </com.github.kostyasha.yad.DockerCloud>
  </clouds>`

Sorry, pasting it in above loses all formatting.

Keep in mind, some of the items found in the config above have been made anonymous for security reasons. Also, the config above doesn't have the explicit slave.jar option for working directory. I removed it to resemble the config at the time when the error occurred.

But definitely the workaround in [#184 (comment)](https://github.com/KostyaSha/yet-another-docker-plugin/issues/184#issuecomment-322996960) fixed the problem.

**Comment by KostyaSha** [comment] 2017-10-11 22:34
5 minutes in debugger and what we have.
1) slave.jar is running with right cwd = /home/jenkins. No bugs in YAD
2) internalDir is "/" here https://github.com/jenkinsci/remoting/blob/0a4dfb7c0d968b39a0e5f146c1f1367a55ed8df4/src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java#L189
that happens because 
![image](https://user-images.githubusercontent.com/231611/31470093-103243cc-aeed-11e7-933c-8eba8b01e47a.png)
and it should be
![image](https://user-images.githubusercontent.com/231611/31470163-5a5dc214-aeed-11e7-9af7-21c20910161a.png)
bug in remoting, i think it should operate under CWD and create it's internal dirs, instead of trying to write to root of the system.

**Comment by oleg-nenashev** [comment] 2017-10-11 22:43
So, from where do you get empty string as parameters?
The default behavior of remoting.jar:
* `workDir is null => workDir is disabled (it has been enabled by something in your case)
* `internalDir` ir `remoting`

I am not sure what happens in your case, but it seems that Remoting gets wrong command line arguments from the launcher.

**Comment by KostyaSha** [comment] 2017-10-11 23:32
```java
/**
 * Parses the connection arguments from JNLP file given in the URL.
 */
hudson.remoting.Launcher#parseJnlpArguments
```
then https://github.com/jenkinsci/jenkins/blob/860d9c54850237303662bd9bddff5545b93b93a7/core/src/main/resources/hudson/slaves/SlaveComputer/slave-agent.jnlp.jelly#L71-L83 
produces
```xml
<jnlp codebase="http://192.168.33.1:8080/jenkins/computer/33_10-3ee51adbc043/" spec="1.0+">
    <information>
        <title>Agent for 33_10-3ee51adbc043</title>
        <vendor>Jenkins project</vendor>
        <homepage href="https://jenkins-ci.org/"/>
    </information>
    <security>
        <all-permissions/>
    </security>
    <resources>
        <j2se version="1.8+"/>
        <jar href="http://192.168.33.1:8080/jenkins/jnlpJars/remoting.jar"/>
    </resources>
    <application-desc main-class="hudson.remoting.jnlp.Main">
        <argument>0d37921d50781a777d00f50b68d8e03a67f91e166040c2d5fb7a4d5969c075ad</argument>
        <argument>33_10-3ee51adbc043</argument>
        <argument>-workDir</argument>
        <argument/>
        <argument>-internalDir</argument>
        <argument/>
        <argument>-url</argument>
        <argument>http://192.168.33.1:8080/jenkins/</argument>
    </application-desc>
</jnlp>
```
that inserts this empty strings into `hudson.remoting.jnlp.Main#_main`

And that piece of xml comes from https://github.com/jenkinsci/jenkins/pull/2945/files#diff-7ef9017286f34a6d3c606235284fa49fR69

**Comment by KostyaSha** [comment] 2017-10-11 23:49
And that is fixed in https://issues.jenkins-ci.org/browse/JENKINS-47056 https://github.com/jenkinsci/jenkins/pull/3034 by @MartinNowak

**Comment by oleg-nenashev** [comment] 2017-10-12 08:10
Marked JENKINS-47056 as LTS candidate

**Comment by KostyaSha** [comment] 2017-10-22 02:12
I think bug not on my side, so closing.

**Closed by KostyaSha** 2017-10-22 02:12 UTC
